const PRODUCTS = [
  {
    id: 1,
    name: "The Initiate",
    tagline: "Your first step into the dungeon",
    price: 24.99,
    originalPrice: null,
    material: "Body-safe silicone",
    size: "Small (3\" insertable)",
    category: "beginner",
    bestseller: true,
    badge: "Best Seller",
    badgeGold: false,
    emoji: "🖤",
    rating: 4.8,
    reviews: 312,
    description: "Tapered tip, flared base, velvety-smooth silicone. The perfect first submission for those new to the art."
  },
  {
    id: 2,
    name: "Crimson Rose",
    tagline: "Blood-red jeweled steel",
    price: 44.99,
    originalPrice: 59.99,
    material: "Surgical steel + crystal",
    size: "Medium (4\" insertable)",
    category: "jeweled",
    bestseller: true,
    badge: "Sale",
    badgeGold: false,
    emoji: "🥀",
    rating: 4.9,
    reviews: 198,
    description: "Polished surgical steel crowned with a deep crimson crystal base. Cold, heavy, and commanding."
  },
  {
    id: 3,
    name: "Iron Warden",
    tagline: "Weighty stainless authority",
    price: 64.99,
    originalPrice: null,
    material: "316L surgical steel",
    size: "Medium (3.5\" insertable)",
    category: "intermediate",
    bestseller: true,
    badge: "Premium",
    badgeGold: true,
    emoji: "⚙️",
    rating: 4.7,
    reviews: 145,
    description: "Mirror-polished surgical steel for commanding weight and total body-safety. Works with any lubricant, easy to sterilize."
  },
  {
    id: 4,
    name: "The Trembler",
    tagline: "10-mode vibrating torment",
    price: 79.99,
    originalPrice: null,
    material: "Platinum silicone",
    size: "Medium (4.5\" insertable)",
    category: "vibrating",
    bestseller: true,
    badge: "New",
    badgeGold: false,
    emoji: "⚡",
    rating: 4.6,
    reviews: 89,
    description: "Whisper-quiet motor with 10 escalating vibration patterns. USB rechargeable, fully waterproof, utterly relentless."
  },
  {
    id: 5,
    name: "Leather Imp",
    tagline: "Tiny & insidiously wearable",
    price: 18.99,
    originalPrice: null,
    material: "Body-safe silicone",
    size: "Extra Small (2.5\" insertable)",
    category: "beginner",
    bestseller: false,
    badge: null,
    badgeGold: false,
    emoji: "🖤",
    rating: 4.5,
    reviews: 203,
    description: "The smallest in our arsenal. Ideal for initiates or all-day wear beneath ordinary life."
  },
  {
    id: 6,
    name: "Obsidian Eye",
    tagline: "Black diamond gem base",
    price: 52.99,
    originalPrice: null,
    material: "Stainless steel + crystal",
    size: "Small (3\" insertable)",
    category: "jeweled",
    bestseller: false,
    badge: null,
    badgeGold: false,
    emoji: "🔮",
    rating: 4.8,
    reviews: 167,
    description: "Polished steel shaft with a jet-black crystal eye at the base. Cold precision meets dark elegance."
  },
  {
    id: 7,
    name: "Chain of Command",
    tagline: "Graduated training set",
    price: 89.99,
    originalPrice: 109.99,
    material: "Platinum silicone",
    size: "Set: S / M / L",
    category: "intermediate",
    bestseller: false,
    badge: "Bundle",
    badgeGold: true,
    emoji: "⛓",
    rating: 4.7,
    reviews: 76,
    description: "Three-piece graduated set. Ascend the ranks at your own pace — small, medium, and large silicone plugs in matching matte black."
  },
  {
    id: 8,
    name: "Dungeon Lord",
    tagline: "For the seasoned master",
    price: 69.99,
    originalPrice: null,
    material: "Platinum silicone",
    size: "Large (5.5\" insertable)",
    category: "advanced",
    bestseller: false,
    badge: null,
    badgeGold: false,
    emoji: "👑",
    rating: 4.4,
    reviews: 55,
    description: "Substantial girth and commanding length for those who have proven their devotion. Not for the uninitiated."
  },
  {
    id: 9,
    name: "The Puppeteer",
    tagline: "Remote-controlled surrender",
    price: 94.99,
    originalPrice: 119.99,
    material: "Platinum silicone",
    size: "Medium (4\" insertable)",
    category: "vibrating",
    bestseller: false,
    badge: "Sale",
    badgeGold: false,
    emoji: "🎭",
    rating: 4.5,
    reviews: 43,
    description: "Wireless remote reaches up to 30 ft. Hand control to your keeper. 12 vibration modes, fully waterproof."
  },
  {
    id: 10,
    name: "Void Glass",
    tagline: "Heavy black glass statement",
    price: 84.99,
    originalPrice: null,
    material: "Borosilicate glass",
    size: "Large (5\" insertable)",
    category: "advanced",
    bestseller: false,
    badge: null,
    badgeGold: false,
    emoji: "🖤",
    rating: 4.6,
    reviews: 38,
    description: "Striking obsidian-black borosilicate glass. Heavy, smooth, and temperature-play ready. Inspect carefully before each use."
  },
  {
    id: 11,
    name: "Scarlet Chain",
    tagline: "Crimson jewel, iron will",
    price: 39.99,
    originalPrice: null,
    material: "Stainless steel + crystal",
    size: "Small (3\" insertable)",
    category: "jeweled",
    bestseller: false,
    badge: "Limited",
    badgeGold: true,
    emoji: "🔴",
    rating: 4.9,
    reviews: 121,
    description: "Polished steel plug with a bold scarlet crystal base. A dungeon classic in limited stock — claim yours."
  },
  {
    id: 12,
    name: "Heartbeat",
    tagline: "Thumping pulse technology",
    price: 109.99,
    originalPrice: null,
    material: "Platinum silicone",
    size: "Medium-Large (4.5\" insertable)",
    category: "vibrating",
    bestseller: false,
    badge: "Premium",
    badgeGold: true,
    emoji: "🩸",
    rating: 4.8,
    reviews: 62,
    description: "Unique thumping motor replicates a deep, rhythmic pulse. 7 escalating patterns. Whisper-quiet. USB rechargeable."
  }
];
