const PRODUCTS = [
  {
    id: 1,
    name: "Velvet Starter",
    tagline: "Perfect first-timer plug",
    price: 24.99,
    originalPrice: null,
    material: "Body-safe silicone",
    size: "Small (3\" insertable)",
    category: "beginner",
    bestseller: true,
    badge: "Best Seller",
    color: "#c084fc",
    emoji: "💜",
    rating: 4.8,
    reviews: 312,
    description: "Tapered tip, flared base, velvety-smooth silicone. Ideal for beginners exploring anal play."
  },
  {
    id: 2,
    name: "Crystal Rose",
    tagline: "Jeweled glass elegance",
    price: 44.99,
    originalPrice: 59.99,
    material: "Borosilicate glass",
    size: "Medium (4\" insertable)",
    category: "jeweled",
    bestseller: true,
    badge: "Sale",
    color: "#f472b6",
    emoji: "🌸",
    rating: 4.9,
    reviews: 198,
    description: "Hand-crafted glass plug with a sparkling gem base. Firm, smooth, temperature-play ready."
  },
  {
    id: 3,
    name: "Steel Luxe",
    tagline: "Weighty stainless perfection",
    price: 64.99,
    originalPrice: null,
    material: "316L surgical steel",
    size: "Medium (3.5\" insertable)",
    category: "intermediate",
    bestseller: true,
    badge: "Premium",
    color: "#94a3b8",
    emoji: "⚙️",
    rating: 4.7,
    reviews: 145,
    description: "Polished surgical steel for satisfying weight and easy cleaning. Works with any lubricant."
  },
  {
    id: 4,
    name: "Rumble Pro",
    tagline: "10-mode vibrating pleasure",
    price: 79.99,
    originalPrice: null,
    material: "Platinum silicone",
    size: "Medium (4.5\" insertable)",
    category: "vibrating",
    bestseller: true,
    badge: "New",
    color: "#34d399",
    emoji: "✨",
    rating: 4.6,
    reviews: 89,
    description: "Whisper-quiet motor with 10 vibration patterns. USB rechargeable, fully waterproof."
  },
  {
    id: 5,
    name: "Petite Pearl",
    tagline: "Tiny & training-perfect",
    price: 18.99,
    originalPrice: null,
    material: "Body-safe silicone",
    size: "Extra Small (2.5\" insertable)",
    category: "beginner",
    bestseller: false,
    badge: null,
    color: "#fbbf24",
    emoji: "🤍",
    rating: 4.5,
    reviews: 203,
    description: "The smallest in our lineup. Great for absolute beginners or wearing throughout the day."
  },
  {
    id: 6,
    name: "Diamond Gem",
    tagline: "Princess-cut crystal base",
    price: 52.99,
    originalPrice: null,
    material: "Stainless steel + crystal",
    size: "Small (3\" insertable)",
    category: "jeweled",
    bestseller: false,
    badge: null,
    color: "#60a5fa",
    emoji: "💎",
    rating: 4.8,
    reviews: 167,
    description: "Polished steel shaft with a genuine Swarovski-inspired crystal base in multiple colors."
  },
  {
    id: 7,
    name: "Stretch Master",
    tagline: "Graduated training set",
    price: 89.99,
    originalPrice: 109.99,
    material: "Platinum silicone",
    size: "Set: S / M / L",
    category: "intermediate",
    bestseller: false,
    badge: "Bundle",
    color: "#f87171",
    emoji: "🎯",
    rating: 4.7,
    reviews: 76,
    description: "Three-piece graduated set. Progress at your own pace with matching silicone plugs in increasing sizes."
  },
  {
    id: 8,
    name: "Deep Dive XL",
    tagline: "For the experienced explorer",
    price: 69.99,
    originalPrice: null,
    material: "Platinum silicone",
    size: "Large (5.5\" insertable)",
    category: "advanced",
    bestseller: false,
    badge: null,
    color: "#a78bfa",
    emoji: "🚀",
    rating: 4.4,
    reviews: 55,
    description: "Substantial girth and length for seasoned users seeking a full, satisfying experience."
  },
  {
    id: 9,
    name: "Buzz Commander",
    tagline: "Remote-controlled vibration",
    price: 94.99,
    originalPrice: 119.99,
    material: "Platinum silicone",
    size: "Medium (4\" insertable)",
    category: "vibrating",
    bestseller: false,
    badge: "Sale",
    color: "#fb923c",
    emoji: "📡",
    rating: 4.5,
    reviews: 43,
    description: "Pairs with a wireless remote up to 30 ft away. 12 vibration modes, fully waterproof."
  },
  {
    id: 10,
    name: "Obsidian King",
    tagline: "Large glass statement piece",
    price: 84.99,
    originalPrice: null,
    material: "Borosilicate glass",
    size: "Large (5\" insertable)",
    category: "advanced",
    bestseller: false,
    badge: null,
    color: "#1e293b",
    emoji: "🖤",
    rating: 4.6,
    reviews: 38,
    description: "Striking black glass plug, thick and smooth. Temperature play-ready, easy to sterilize."
  },
  {
    id: 11,
    name: "Rainbow Gem",
    tagline: "Pride edition jeweled plug",
    price: 39.99,
    originalPrice: null,
    material: "Stainless steel + crystal",
    size: "Small (3\" insertable)",
    category: "jeweled",
    bestseller: false,
    badge: "Limited",
    color: "#ec4899",
    emoji: "🌈",
    rating: 4.9,
    reviews: 121,
    description: "Celebrate in style. Polished steel plug with a rainbow crystal base. Limited quantities."
  },
  {
    id: 12,
    name: "Thump & Pulse",
    tagline: "Thumping motor technology",
    price: 109.99,
    originalPrice: null,
    material: "Platinum silicone",
    size: "Medium-Large (4.5\" insertable)",
    category: "vibrating",
    bestseller: false,
    badge: "Premium",
    color: "#6366f1",
    emoji: "💫",
    rating: 4.8,
    reviews: 62,
    description: "Unique thumping motor replicates a heartbeat-like sensation. 7 patterns, whisper-quiet."
  }
];
